---
title: Marcos Ramon
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    image: assets/images/gephi2.png
url: https://marcosramon.net
baseurl: 
twitter:
  username: mrtollens
author:
  twitter: mrtollens
brand_color: amber-300
permalink: posts/:title/
google_analytics: ''
lang: pt
num_posts_visible_initially: 5
date_format: "%b %-d, %Y"
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- mix-manifest.json
- webpack.mix.js
- yarn.lock
- package.json
- hot
- LICENSE.txt
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
- jemoji
- jekyll-readme-index
